### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by maunoxyd** [miaolz123/vue-markdown#38] opened 2017-07-29 10:28 UTC
Got this in console with latest version:
`[Vue warn]: Invalid default value for prop "anchorAttributes": Props with type Object/Array must use a factory function to return the default value.`
I'm getting content from contentful and it's getting displayed though.

**Comment by miaolz123** [comment] 2017-07-31 04:24
Duplicate of #36

**Closed by miaolz123** 2017-07-31 04:24 UTC
